name: Remote SSH Copy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files to Remote Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the private key secret, not password
          port: ${{ secrets.SSH_PORT }}  # If you have a custom SSH port
          script: |
            cd /home/kurtcibx/docs.solve3.org  # Replace with your target directory
            scp -rf ./* .
